kind: pipeline
name: default

platform:
  os: windows
  arch: amd64

steps:
- name: do-stuff
  image: microsoft/windowsservercore:1803
  commands:
  - dir c:\
  - whoami

- name: and
  image: microsoft/windowsservercore:1803
  commands:
  - ping 1.1.1.1