kind: pipeline
name: windows-backend

platform:
  os: windows
  arch: amd64

steps:
- name: do-stuff
  image: microsoft/windowsservercore:1803
  commands:
  - dir c:\
  - whoami

- name: and
  image: microsoft/windowsservercore:1803
  commands:
  - dir
  - dir env:\ | Out-String
---
kind: pipeline
name: windows-frontend

platform:
  os: windows
  arch: amd64

steps:
- name: build
  image: microsoft/windowsservercore:1803
  commands:
  - dir env:\ | Out-String
---
kind: pipeline
name: linux-backend

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: alpine
  commands:
  - ls
---
kind: pipeline
name: after

depends_on:
- windows-backend
- windows-frontend
- linux-backend