kind: pipeline
name: windows-backend

platform:
  os: windows
  arch: amd64

steps:
- name: do-stuff
  image: microsoft/windowsservercore:1803
  commands:
  - dir c:\
  - whoami

---
kind: pipeline
name: windows-frontend

platform:
  os: windows
  arch: amd64

steps:
- name: build
  image: microsoft/windowsservercore:1803
  commands:
  - dir env:\ | Out-String

---
kind: pipeline
name: linux-backend

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: alpine
  commands:
  - ls

---
kind: pipeline
name: after

clone:
  disable: true

steps:
- name: notify
  image: alpine
  commands:
  - ls

depends_on:
- windows-backend
- windows-frontend
- linux-backend

trigger:
  status:
  - success
  - failure